name: Deploying pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    name: Deployment pipeline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: npm run build
        run: npm run build
      - name: install cross-end
        run: npm install --save-dev cross-env
      - name: install async-errors
        run: npm install express-async-errors --save
      - name: install mongoose
        run: npm install mongoose
      - name: install unique-validator      
        run: npm install --save mongoose-unique-validator
      - name: install jsonwebtoken
        run: npm install jsonwebtoken
      - name: install bcrypt
        run: npm install bcrypt
      - name: install supertest
        run: npm install supertest --save-dev
      - name: npm run test
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET}}
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: 'http://localhost:3001'
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET}}